version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  # Disabling all Dependabot PRs until further notice:
  open-pull-requests-limit: 0
  ignore:
  - dependency-name: io.dropwizard.metrics:metrics-core
    versions:
    - 4.1.17
    - 4.1.18
    - 4.1.19
  - dependency-name: com.google.auto.value:auto-value
    versions:
    - 1.7.5
    - "1.8"
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.google.inject:guice
    versions:
    - 5.0.0
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.8.0
  - dependency-name: com.github.ben-manes.caffeine:caffeine
    versions:
    - 2.9.0
    - 3.0.0
  - dependency-name: org.testcontainers:testcontainers
    versions:
    - 1.15.2
  - dependency-name: com.google.errorprone:error_prone_annotations
    versions:
    - 2.5.1
  - dependency-name: com.google.errorprone:error_prone_core
    versions:
    - 2.5.1
